# Generated by Django 5.0.2 on 2024-04-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('AD', 'Advertiser'), ('C', 'Client'), ('O', 'Organizer'), ('SA', 'Super Admin')], default='C', max_length=10),
        ),
    ]
