# Generated by Django 5.0.2 on 2024-04-13 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_useraccount_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='End_Date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='Start_Date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
    ]
