# Generated by Django 5.0.2 on 2024-03-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_useraccount_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_name',
            new_name='name',
        ),
    ]
