# Generated by Django 5.0.2 on 2024-03-18 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_field', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('situation', models.CharField(choices=[('SUB', 'Subscriper'), ('UNSUB', 'UnSubscriper'), ('B', 'Blocked')], default='UNSUB', max_length=10)),
                ('place_capacity', models.IntegerField(default=0)),
                ('place_name', models.CharField(max_length=30)),
                ('link', models.URLField(unique=True)),
                ('axis_x', models.FloatField(default=0, max_length=9)),
                ('axis_y', models.FloatField(default=0, max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ManyToManyField(to='Advertiser.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvertiserAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.advertiser')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.attachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('price_for_one', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=250)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('advertiser_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.advertiser')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer_Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.attachment')),
                ('offer_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('offer_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
