# Generated by Django 5.0.2 on 2024-07-18 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Advertiser', '0001_initial'),
        ('Core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertiserattachments',
            name='advertiser_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_attachments', to='Advertiser.advertiser'),
        ),
        migrations.AddField(
            model_name='advertiserattachments',
            name='attachment_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.attachment'),
        ),
        migrations.AddField(
            model_name='offer',
            name='advertiser_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Advertiser.advertiser'),
        ),
        migrations.AddField(
            model_name='offer_attachments',
            name='attachment_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.attachment'),
        ),
        migrations.AddField(
            model_name='offer_attachments',
            name='offer_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_attachments', to='Advertiser.offer'),
        ),
        migrations.AddField(
            model_name='offerrequest',
            name='offer_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_requests', to='Advertiser.offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.service'),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='service',
            field=models.ManyToManyField(to='Advertiser.service'),
        ),
    ]
