# Generated by Django 5.0.2 on 2024-04-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0003_remove_advertiser_name_alter_offer_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='service_id',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='offer',
            name='advertiser_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='Advertiser.advertiser'),
        ),
    ]
