# Generated by Django 5.0.2 on 2024-04-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0004_rename_service_id_offer_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_attachments',
            name='offer_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_attachments', to='Advertiser.offer'),
        ),
    ]
