# Generated by Django 5.0.2 on 2024-04-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0005_alter_offer_attachments_offer_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='num_of_seat',
            field=models.IntegerField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
