# Generated by Django 5.0.2 on 2024-04-19 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0006_offer_num_of_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerrequest',
            old_name='offer_object',
            new_name='offer',
        ),
    ]
