# Generated by Django 5.0.2 on 2024-04-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0008_rename_offer_offerrequest_offer_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerrequest',
            old_name='quantity',
            new_name='num_of_seat',
        ),
    ]
