# Generated by Django 5.0.2 on 2024-04-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0010_alter_offerrequest_offer_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertiserattachments',
            old_name='attachment',
            new_name='attachment_object',
        ),
    ]
