# Generated by Django 5.0.2 on 2024-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0012_alter_advertiserattachments_advertiser_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='num_of_seat',
            field=models.IntegerField(),
        ),
    ]
