# Generated by Django 5.0.2 on 2024-07-30 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Tour_Organizer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='client_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_requests', to='Client.client'),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='tour_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_requests', to='Tour_Organizer.tour'),
        ),
        migrations.AddField(
            model_name='comment',
            name='client_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_comments', to='Client.client'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_comments', to='Tour_Organizer.tour'),
        ),
    ]
