# Generated by Django 5.0.2 on 2024-03-12 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0001_initial'),
        ('Tour_Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tour_Organizer.tour'),
        ),
    ]
