# Generated by Django 5.0.2 on 2024-05-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_initial'),
        ('Tour_Organizer', '0002_tourpoint_title_alter_tourpoint_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_comments', to='Tour_Organizer.tour'),
        ),
    ]
