# Generated by Django 5.0.2 on 2024-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_remove_comment_comments_field_comment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientrequest',
            name='situation',
            field=models.CharField(choices=[('W', 'Waiting'), ('A', 'Accepted'), ('R', 'Rejected')], default='W', max_length=25),
        ),
    ]
