# Generated by Django 5.0.2 on 2024-03-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourorganizer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
