# Generated by Django 5.0.2 on 2024-06-06 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_Organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_tours', to='Tour_Organizer.tourorganizer'),
        ),
    ]
