# Generated by Django 5.0.2 on 2024-04-13 22:39

import Tour_Organizer.models.tour_organizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_Organizer', '0002_alter_tourorganizer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='comment_counter',
        ),
        migrations.RemoveField(
            model_name='tourpoint',
            name='title',
        ),
        migrations.AlterField(
            model_name='tourorganizer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=Tour_Organizer.models.tour_organizer.upload_to),
        ),
    ]
