# Generated by Django 5.0.2 on 2024-04-23 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertiser', '0012_alter_advertiserattachments_advertiser_object'),
        ('Tour_Organizer', '0003_remove_tour_comment_counter_remove_tourpoint_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpoint',
            name='offer_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Advertiser.offerrequest'),
        ),
    ]
