# Generated by Django 5.0.2 on 2024-04-24 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tour_Organizer', '0004_alter_tourpoint_offer_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='posted',
            field=models.BooleanField(default=0),
        )
    ]
